### ISSUE TITLE
Cannot import master branch

### ISSUE THREAD

**Issue by mikebutak** [RedHatOfficial/miq-Utilities#168]
When I try to import the master branch, I get the following error in MIQ:

![image](https://user-images.githubusercontent.com/34036100/84922376-9de8cd80-b07a-11ea-97f7-5fbab2fb02c5.png)

Instead I imported tag v12.1, which worked.  

Is there a problem with using v12.1 until the issue with the master branch is resolved?

**Comment by itewk** [comment]
@curt-matthews @A-Beck either you available to help?

**Comment by A-Beck** [comment]
@itewk sure thing
@mikebutak can you import this branch?
https://github.com/RedHatOfficial/miq-Utilities/tree/168-fix-import

**Comment by mikebutak** [comment]
Yes @A-Beck I was able to import that branch without error.  @angapov perhaps this addresses the same fix you made offline?
